<a href="https://colab.research.google.com/github/raeyaanmuppaneni/EMG-controlled-robotic-arm/blob/main/Cross_Validation_Classification_Model_Building.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Load the CSV files

In [ ]:
# define the paths

# Raw Data
#DATA_CSV = "/content/drive/MyDrive/Technology and Trainings/Python and AI/Raeyaan/Raeyaan shared folder/Exoskeleton Project/Dataset/Raeyaan Dataset/combined_data_EMG_envelop.csv"

# Processed Data
DATA_CSV = "/content/drive/MyDrive/Raeyaan shared folder/Exoskeleton Project/Dataset/Raeyaan Dataset/combined_data_EMG_envelop_20_7.csv"

#Featurized using ts-fresh
#DATA_CSV = "/content/drive/MyDrive/Raeyaan shared folder/Exoskeleton Project/Dataset/Raeyaan Dataset/tsfresh.csv"

#Featurized using librosa/mfcc
#DATA_CSV = "/content/drive/MyDrive/Raeyaan shared folder/Exoskeleton Project/Dataset/Raeyaan Dataset/mfcc.csv"

In [ ]:
import pandas as pd

# load the train csv
data = pd.read_csv(DATA_CSV)

data.head()

,exo_project_emg_1_emg_envelop_0,exo_project_emg_1_emg_envelop_1,exo_project_emg_1_emg_envelop_2,exo_project_emg_1_emg_envelop_3,exo_project_emg_1_emg_envelop_4,exo_project_emg_1_emg_envelop_5,exo_project_emg_1_emg_envelop_6,exo_project_emg_1_emg_envelop_7,exo_project_emg_1_emg_envelop_8,exo_project_emg_1_emg_envelop_9,...,exo_project_emg_1_emg_envelop_51,exo_project_emg_1_emg_envelop_52,exo_project_emg_1_emg_envelop_53,exo_project_emg_1_emg_envelop_54,exo_project_emg_1_emg_envelop_55,exo_project_emg_1_emg_envelop_56,exo_project_emg_1_emg_envelop_57,exo_project_emg_1_emg_envelop_58,exo_project_emg_1_emg_envelop_59,Folder
0,30,30,32,32,32,34,38,38,42,46,...,138,138,148,154,166,180,190,208,208,Hand Lift
1,324,328,330,332,332,334,336,338,342,344,...,410,416,424,424,430,434,434,432,436,Hand Lift
2,356,354,352,350,350,350,348,348,346,346,...,330,328,324,328,328,332,334,338,340,Hand Lift
3,40,40,38,38,38,38,38,38,38,38,...,174,182,184,188,190,190,190,192,196,Hand Lift
4,240,240,240,240,240,240,242,242,246,246,...,384,384,388,388,392,390,390,386,382,Hand Lift

In [ ]:
data["Folder"].unique()

array(['Hand Lift', 'Wrist Lift', 'Hand Twist', 'Normal'], dtype=object)

### Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split

# split the data
train_df, test_df = train_test_split(data, test_size = 0.2,stratify=data['Folder'])

In [ ]:
test_df.to_csv("/content/drive/MyDrive/Raeyaan shared folder/Exoskeleton Project/Dataset/Raeyaan Dataset/raw_EMG_test_20_7.csv",index = False)

In [ ]:
test_df['Folder'].value_counts()

Folder
Hand Lift     14
Normal        14
Wrist Lift    14
Hand Twist    14
Name: count, dtype: int64

In [ ]:
X = train_df.drop(columns = ["Folder"])
y = train_df["Folder"]

### Encoding Labels

In [ ]:
LABEL_COLUMN = "Folder"

In [ ]:
# labels are there as string otherwise words
# need to convert the labels into numbers
print(train_df[LABEL_COLUMN].value_counts())
LABELS = list(train_df[LABEL_COLUMN].unique())
# sort the labels
LABELS.sort()
print(LABELS.sort())

Folder
Wrist Lift    56
Normal        56
Hand Twist    56
Hand Lift     56
Name: count, dtype: int64
None

In [ ]:
# convert into numbers
train_df[LABEL_COLUMN] = pd.factorize(train_df[LABEL_COLUMN], sort = True)[0]
train_df[LABEL_COLUMN].value_counts()

Folder
3    56
2    56
1    56
0    56
Name: count, dtype: int64

### Seperate features and labels

In [ ]:
# get all features without the labels
# all the rows
# all the columns without the last column
X = train_df.drop(LABEL_COLUMN, axis = 1).values
# all rows
# only the lastb column, which is the label
Y = train_df[LABEL_COLUMN].values

### Train the Model using Cross Validation

In [ ]:

from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score
import numpy as np

def cross_validation(model, data = (X, Y), splits = 5):
    kf = KFold(n_splits=splits, shuffle=True, random_state=42)

    # Perform k-fold cross-validation
    accuracy = []
    precision = []
    recall = []

    for train_index, valid_index in kf.split(data[0]):
        X_train, X_valid = data[0][train_index], data[0][valid_index]
        y_train, y_valid = data[1][train_index], data[1][valid_index]

        # Fit the defined model
        model.fit(X_train, y_train)

        # Make predictions on the test data
        y_pred = model.predict(X_valid)

        # Calculate accuracy, precision and recall
        accuracy.append(accuracy_score(y_pred, y_valid))
        precision.append(precision_score(y_pred, y_valid, average = 'micro'))
        recall.append(recall_score(y_pred, y_valid, average = 'micro'))


    # get arrays
    accuracy_set = np.array(accuracy)
    precision_set = np.array(precision)
    recall_set = np.array(recall)

    print("Mean Accuracy: {}".format(accuracy_set.mean()))
    print("Mean Precision: {}".format(precision_set.mean()))
    print("Mean Recall: {}".format(recall_set.mean()))
    return accuracy_set.mean()

### Logistic Regression

### KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Use 5-fold cross validation for hyper-parameter tuning
# Try out different values and choose the best hyper-parameters
results = []
for i in range(1,15):
  knn = KNeighborsClassifier(n_neighbors=i) # vary n_neighbours from 1 to 20
  result = cross_validation(knn)
  results.append(result)

Mean Accuracy: 0.6524242424242425
Mean Precision: 0.6524242424242425
Mean Recall: 0.6524242424242425
Mean Accuracy: 0.6564646464646465
Mean Precision: 0.6564646464646465
Mean Recall: 0.6564646464646465
Mean Accuracy: 0.6878787878787879
Mean Precision: 0.6878787878787879
Mean Recall: 0.6878787878787879
Mean Accuracy: 0.6565656565656566
Mean Precision: 0.6565656565656566
Mean Recall: 0.6565656565656566
Mean Accuracy: 0.6254545454545454
Mean Precision: 0.6254545454545454
Mean Recall: 0.6254545454545454
Mean Accuracy: 0.6698989898989899
Mean Precision: 0.6698989898989899
Mean Recall: 0.6698989898989899
Mean Accuracy: 0.6565656565656566
Mean Precision: 0.6565656565656566
Mean Recall: 0.6565656565656566
Mean Accuracy: 0.6653535353535354
Mean Precision: 0.6653535353535354
Mean Recall: 0.6653535353535354
Mean Accuracy: 0.6786868686868687
Mean Precision: 0.6786868686868687
Mean Recall: 0.6786868686868687
Mean Accuracy: 0.6831313131313131
Mean Precision: 0.6831313131313131
Mean Recall: 0.6831313131313131
Mean Accuracy: 0.6875757575757576
Mean Precision: 0.6875757575757576
Mean Recall: 0.6875757575757576
Mean Accuracy: 0.6964646464646465
Mean Precision: 0.6964646464646465
Mean Recall: 0.6964646464646465
Mean Accuracy: 0.7054545454545454
Mean Precision: 0.7054545454545454
Mean Recall: 0.7054545454545454
Mean Accuracy: 0.6965656565656566
Mean Precision: 0.6965656565656566
Mean Recall: 0.6965656565656566

In [ ]:
for i in results:
  print(round(i,2))

0.65
0.66
0.69
0.66
0.63
0.67
0.66
0.67
0.68
0.68
0.69
0.7
0.71
0.7

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Use 5-fold cross validation for hyper-parameter tuning
# Try out different values and choose the best hyper-parameters
knn = KNeighborsClassifier(n_neighbors=5) # vary n_neighbours from 1 to 20
model = knn.fit(X_train, y_train)

NameError: name 'X_train' is not defined

NameError: name 'model' is not defined

### Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Use 5-fold cross validation for hyper-parameter tuning
# Try out different values and choose the best hyper-parameters
depth = [2,3,4,5,6,7]
width = [10,20,30,40,50,60,70,80,90,100]
results = []
for i in depth:
  temp = []
  for k in width:
    rf = RandomForestClassifier(n_estimators=k, max_depth = i) # vary n_estimators from 10 to 100 and max_depth from 1 to 10
    result = cross_validation(rf)
    temp.append(result)
  results.append(temp)

Mean Accuracy: 0.6209090909090909
Mean Precision: 0.6209090909090909
Mean Recall: 0.6209090909090909
Mean Accuracy: 0.6658585858585859
Mean Precision: 0.6658585858585859
Mean Recall: 0.6658585858585859
Mean Accuracy: 0.6478787878787878
Mean Precision: 0.6478787878787878
Mean Recall: 0.6478787878787878
Mean Accuracy: 0.6386868686868687
Mean Precision: 0.6386868686868687
Mean Recall: 0.6386868686868687
Mean Accuracy: 0.6476767676767677
Mean Precision: 0.6476767676767677
Mean Recall: 0.6476767676767677
Mean Accuracy: 0.6251515151515151
Mean Precision: 0.6251515151515151
Mean Recall: 0.6251515151515151
Mean Accuracy: 0.6476767676767677
Mean Precision: 0.6476767676767677
Mean Recall: 0.6476767676767677
Mean Accuracy: 0.6477777777777778
Mean Precision: 0.6477777777777778
Mean Recall: 0.6477777777777778
Mean Accuracy: 0.6252525252525252
Mean Precision: 0.6252525252525252
Mean Recall: 0.6252525252525252
Mean Accuracy: 0.6431313131313131
Mean Precision: 0.6431313131313131
Mean Recall: 0.6431313131313131
Mean Accuracy: 0.7053535353535353
Mean Precision: 0.7053535353535353
Mean Recall: 0.7053535353535353
Mean Accuracy: 0.7097979797979799
Mean Precision: 0.7097979797979799
Mean Recall: 0.7097979797979799
Mean Accuracy: 0.7054545454545454
Mean Precision: 0.7054545454545454
Mean Recall: 0.7054545454545454
Mean Accuracy: 0.7008080808080808
Mean Precision: 0.7008080808080808
Mean Recall: 0.7008080808080808
Mean Accuracy: 0.7053535353535353
Mean Precision: 0.7053535353535353
Mean Recall: 0.7053535353535353
Mean Accuracy: 0.7053535353535354
Mean Precision: 0.7053535353535354
Mean Recall: 0.7053535353535354
Mean Accuracy: 0.7053535353535353
Mean Precision: 0.7053535353535353
Mean Recall: 0.7053535353535353
Mean Accuracy: 0.7053535353535353
Mean Precision: 0.7053535353535353
Mean Recall: 0.7053535353535353
Mean Accuracy: 0.7097979797979798
Mean Precision: 0.7097979797979798
Mean Recall: 0.7097979797979798
Mean Accuracy: 0.7142424242424242
Mean Precision: 0.7142424242424242
Mean Recall: 0.7142424242424242
Mean Accuracy: 0.7098989898989899
Mean Precision: 0.7098989898989899
Mean Recall: 0.7098989898989899
Mean Accuracy: 0.6964646464646465
Mean Precision: 0.6964646464646465
Mean Recall: 0.6964646464646465
Mean Accuracy: 0.7142424242424241
Mean Precision: 0.7142424242424241
Mean Recall: 0.7142424242424241
Mean Accuracy: 0.7097979797979799
Mean Precision: 0.7097979797979799
Mean Recall: 0.7097979797979799
Mean Accuracy: 0.7008080808080808
Mean Precision: 0.7008080808080808
Mean Recall: 0.7008080808080808
Mean Accuracy: 0.7097979797979798
Mean Precision: 0.7097979797979798
Mean Recall: 0.7097979797979798
Mean Accuracy: 0.7053535353535353
Mean Precision: 0.7053535353535353
Mean Recall: 0.7053535353535353
Mean Accuracy: 0.7142424242424242
Mean Precision: 0.7142424242424242
Mean Recall: 0.7142424242424242
Mean Accuracy: 0.7186868686868687
Mean Precision: 0.7186868686868687
Mean Recall: 0.7186868686868687
Mean Accuracy: 0.7142424242424242
Mean Precision: 0.7142424242424242
Mean Recall: 0.7142424242424242
Mean Accuracy: 0.7231313131313131
Mean Precision: 0.7231313131313131
Mean Recall: 0.7231313131313131
Mean Accuracy: 0.7098989898989899
Mean Precision: 0.7098989898989899
Mean Recall: 0.7098989898989899
Mean Accuracy: 0.6875757575757576
Mean Precision: 0.6875757575757576
Mean Recall: 0.6875757575757576
Mean Accuracy: 0.7011111111111111
Mean Precision: 0.7011111111111111
Mean Recall: 0.7011111111111111
Mean Accuracy: 0.6964646464646465
Mean Precision: 0.6964646464646465
Mean Recall: 0.6964646464646465
Mean Accuracy: 0.7054545454545454
Mean Precision: 0.7054545454545454
Mean Recall: 0.7054545454545454
Mean Accuracy: 0.692020202020202
Mean Precision: 0.692020202020202
Mean Recall: 0.692020202020202
Mean Accuracy: 0.6965656565656566
Mean Precision: 0.6965656565656566
Mean Recall: 0.6965656565656566
Mean Accuracy: 0.6964646464646465
Mean Precision: 0.6964646464646465
Mean Recall: 0.6964646464646465
Mean Accuracy: 0.6965656565656566
Mean Precision: 0.6965656565656566
Mean Recall: 0.6965656565656566
Mean Accuracy: 0.7236363636363636
Mean Precision: 0.7236363636363636
Mean Recall: 0.7236363636363636
Mean Accuracy: 0.6964646464646465
Mean Precision: 0.6964646464646465
Mean Recall: 0.6964646464646465
Mean Accuracy: 0.7011111111111111
Mean Precision: 0.7011111111111111
Mean Recall: 0.7011111111111111
Mean Accuracy: 0.7056565656565656
Mean Precision: 0.7056565656565656
Mean Recall: 0.7056565656565656
Mean Accuracy: 0.6966666666666667
Mean Precision: 0.6966666666666667
Mean Recall: 0.6966666666666667
Mean Accuracy: 0.6786868686868688
Mean Precision: 0.6786868686868688
Mean Recall: 0.6786868686868688
Mean Accuracy: 0.678888888888889
Mean Precision: 0.678888888888889
Mean Recall: 0.678888888888889
Mean Accuracy: 0.7053535353535354
Mean Precision: 0.7053535353535354
Mean Recall: 0.7053535353535354
Mean Accuracy: 0.6786868686868687
Mean Precision: 0.6786868686868687
Mean Recall: 0.6786868686868687
Mean Accuracy: 0.7010101010101011
Mean Precision: 0.7010101010101011
Mean Recall: 0.7010101010101011
Mean Accuracy: 0.6923232323232323
Mean Precision: 0.6923232323232323
Mean Recall: 0.6923232323232323
Mean Accuracy: 0.6831313131313131
Mean Precision: 0.6831313131313131
Mean Recall: 0.6831313131313131
Mean Accuracy: 0.6832323232323233
Mean Precision: 0.6832323232323233
Mean Recall: 0.6832323232323233
Mean Accuracy: 0.6875757575757576
Mean Precision: 0.6875757575757576
Mean Recall: 0.6875757575757576
Mean Accuracy: 0.6875757575757576
Mean Precision: 0.6875757575757576
Mean Recall: 0.6875757575757576
Mean Accuracy: 0.6832323232323233
Mean Precision: 0.6832323232323233
Mean Recall: 0.6832323232323233
Mean Accuracy: 0.6787878787878787
Mean Precision: 0.6787878787878787
Mean Recall: 0.6787878787878787
Mean Accuracy: 0.6786868686868687
Mean Precision: 0.6786868686868687
Mean Recall: 0.6786868686868687
Mean Accuracy: 0.6787878787878789
Mean Precision: 0.6787878787878789
Mean Recall: 0.6787878787878789
Mean Accuracy: 0.6922222222222223
Mean Precision: 0.6922222222222223
Mean Recall: 0.6922222222222223

In [ ]:
rounded_data = [[round(value, 2) for value in row] for row in results]
for i in rounded_data:
  print("\t".join(map(str, i))) # Tab-separated values

0.62	0.67	0.65	0.64	0.65	0.63	0.65	0.65	0.63	0.64
0.71	0.71	0.71	0.7	0.71	0.71	0.71	0.71	0.71	0.71
0.71	0.7	0.71	0.71	0.7	0.71	0.71	0.71	0.72	0.71
0.72	0.71	0.69	0.7	0.7	0.71	0.69	0.7	0.7	0.7
0.72	0.7	0.7	0.71	0.7	0.68	0.68	0.71	0.68	0.7
0.69	0.68	0.68	0.69	0.69	0.68	0.68	0.68	0.68	0.69

##MLP

In [ ]:
from sklearn.neural_network import MLPClassifier

# Use 5-fold cross validation for hyper-parameter tuning
# Try out different values and choose the best hyper-parameters
mlp = MLPClassifier(learning_rate_init=0.0001, max_iter=100) # vary learning rate as 0.0001, 0.001, 0.01, 0.05, 0.1, 1 and max_iter from 10 to 100

cross_validation(mlp)

Mean Accuracy: 0.2006060606060606
Mean Precision: 0.2006060606060606
Mean Recall: 0.2006060606060606

np.float64(0.2006060606060606)

In [ ]:
from sklearn.neural_network import MLPClassifier
import numpy as np
  # Use 5-fold cross validation for hyper-parameter tuning
  # Try out different values and choose the best hyper-parameters
lr = [0.05, 0.01, 0.005, 0.001, 0.0005, 0.0001]
epochs = [20,40,60,80,100,120,140,160,180,200]
results = []

for i in lr:
  temp = []
  for j in epochs:
    mlp = MLPClassifier(hidden_layer_sizes=(200,100,50,), learning_rate_init=i, max_iter=j) # vary learning rate as 0.0001, 0.001, 0.01, 0.05, 0.1, 1 and max_iter from 10 to 100
    print(f"learning rate {i}, epochs {j}")
    result = cross_validation(mlp)
    temp.append(result)
  results.append(temp)

learning rate 0.05, epochs 20

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.2413131313131313
Mean Precision: 0.2413131313131313
Mean Recall: 0.2413131313131313
learning rate 0.05, epochs 40

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.2011111111111111
Mean Precision: 0.2011111111111111
Mean Recall: 0.2011111111111111
learning rate 0.05, epochs 60

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.24575757575757576
Mean Precision: 0.24575757575757576
Mean Recall: 0.24575757575757576
learning rate 0.05, epochs 80

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (80) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.24525252525252522
Mean Precision: 0.24525252525252522
Mean Recall: 0.24525252525252522
learning rate 0.05, epochs 100
Mean Accuracy: 0.2411111111111111
Mean Precision: 0.2411111111111111
Mean Recall: 0.2411111111111111
learning rate 0.05, epochs 120
Mean Accuracy: 0.1874747474747475
Mean Precision: 0.1874747474747475
Mean Recall: 0.1874747474747475
learning rate 0.05, epochs 140

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (140) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.2808080808080808
Mean Precision: 0.2808080808080808
Mean Recall: 0.2808080808080808
learning rate 0.05, epochs 160
Mean Accuracy: 0.2408080808080808
Mean Precision: 0.2408080808080808
Mean Recall: 0.2408080808080808
learning rate 0.05, epochs 180
Mean Accuracy: 0.2501010101010101
Mean Precision: 0.2501010101010101
Mean Recall: 0.2501010101010101
learning rate 0.05, epochs 200
Mean Accuracy: 0.19636363636363638
Mean Precision: 0.19636363636363638
Mean Recall: 0.19636363636363638
learning rate 0.01, epochs 20

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.2413131313131313
Mean Precision: 0.2413131313131313
Mean Recall: 0.2413131313131313
learning rate 0.01, epochs 40

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.3433333333333333
Mean Precision: 0.3433333333333333
Mean Recall: 0.3433333333333333
learning rate 0.01, epochs 60

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.3762626262626262
Mean Precision: 0.3762626262626262
Mean Recall: 0.3762626262626262
learning rate 0.01, epochs 80

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (80) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (80) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (80) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.46797979797979794
Mean Precision: 0.46797979797979794
Mean Recall: 0.46797979797979794
learning rate 0.01, epochs 100

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.47191919191919185
Mean Precision: 0.47191919191919185
Mean Recall: 0.47191919191919185
learning rate 0.01, epochs 120

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (120) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (120) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (120) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.5267676767676768
Mean Precision: 0.5267676767676768
Mean Recall: 0.5267676767676768
learning rate 0.01, epochs 140

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (140) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (140) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.5624242424242424
Mean Precision: 0.5624242424242424
Mean Recall: 0.5624242424242424
learning rate 0.01, epochs 160
Mean Accuracy: 0.48292929292929293
Mean Precision: 0.48292929292929293
Mean Recall: 0.48292929292929293
learning rate 0.01, epochs 180

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (180) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (180) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.5255555555555556
Mean Precision: 0.5255555555555556
Mean Recall: 0.5255555555555556
learning rate 0.01, epochs 200

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.5351515151515152
Mean Precision: 0.5351515151515152
Mean Recall: 0.5351515151515152
learning rate 0.005, epochs 20

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.3435353535353535
Mean Precision: 0.3435353535353535
Mean Recall: 0.3435353535353535
learning rate 0.005, epochs 40

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.2545454545454545
Mean Precision: 0.2545454545454545
Mean Recall: 0.2545454545454545
learning rate 0.005, epochs 60

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.2896969696969697
Mean Precision: 0.2896969696969697
Mean Recall: 0.2896969696969697
learning rate 0.005, epochs 80

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (80) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (80) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.3583838383838384
Mean Precision: 0.3583838383838384
Mean Recall: 0.3583838383838384
learning rate 0.005, epochs 100

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.4414141414141414
Mean Precision: 0.4414141414141414
Mean Recall: 0.4414141414141414
learning rate 0.005, epochs 120

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (120) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.29
Mean Precision: 0.29
Mean Recall: 0.29
learning rate 0.005, epochs 140
Mean Accuracy: 0.3433333333333333
Mean Precision: 0.3433333333333333
Mean Recall: 0.3433333333333333
learning rate 0.005, epochs 160

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (160) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (160) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (160) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.42979797979797973
Mean Precision: 0.42979797979797973
Mean Recall: 0.42979797979797973
learning rate 0.005, epochs 180
Mean Accuracy: 0.3522222222222222
Mean Precision: 0.3522222222222222
Mean Recall: 0.3522222222222222
learning rate 0.005, epochs 200

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.3764646464646465
Mean Precision: 0.3764646464646465
Mean Recall: 0.3764646464646465
learning rate 0.001, epochs 20

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.2635353535353535
Mean Precision: 0.2635353535353535
Mean Recall: 0.2635353535353535
learning rate 0.001, epochs 40

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.2812121212121212
Mean Precision: 0.2812121212121212
Mean Recall: 0.2812121212121212
learning rate 0.001, epochs 60

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.47838383838383836
Mean Precision: 0.47838383838383836
Mean Recall: 0.47838383838383836
learning rate 0.001, epochs 80

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (80) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (80) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (80) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.4722222222222222
Mean Precision: 0.4722222222222222
Mean Recall: 0.4722222222222222
learning rate 0.001, epochs 100

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.3404040404040404
Mean Precision: 0.3404040404040404
Mean Recall: 0.3404040404040404
learning rate 0.001, epochs 120

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (120) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (120) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.5007070707070708
Mean Precision: 0.5007070707070708
Mean Recall: 0.5007070707070708
learning rate 0.001, epochs 140

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (140) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (140) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (140) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (140) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.5137373737373737
Mean Precision: 0.5137373737373737
Mean Recall: 0.5137373737373737
learning rate 0.001, epochs 160

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (160) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.30333333333333334
Mean Precision: 0.30333333333333334
Mean Recall: 0.30333333333333334
learning rate 0.001, epochs 180

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (180) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (180) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (180) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (180) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.5173737373737374
Mean Precision: 0.5173737373737374
Mean Recall: 0.5173737373737374
learning rate 0.001, epochs 200

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.34878787878787876
Mean Precision: 0.34878787878787876
Mean Recall: 0.34878787878787876
learning rate 0.0005, epochs 20

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.23252525252525252
Mean Precision: 0.23252525252525252
Mean Recall: 0.23252525252525252
learning rate 0.0005, epochs 40

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.3180808080808081
Mean Precision: 0.3180808080808081
Mean Recall: 0.3180808080808081
learning rate 0.0005, epochs 60

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.4280808080808082
Mean Precision: 0.4280808080808082
Mean Recall: 0.4280808080808082
learning rate 0.0005, epochs 80

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (80) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (80) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (80) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (80) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.39262626262626255
Mean Precision: 0.39262626262626255
Mean Recall: 0.39262626262626255
learning rate 0.0005, epochs 100

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.3480808080808081
Mean Precision: 0.3480808080808081
Mean Recall: 0.3480808080808081
learning rate 0.0005, epochs 120

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (120) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (120) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.4412121212121212
Mean Precision: 0.4412121212121212
Mean Recall: 0.4412121212121212
learning rate 0.0005, epochs 140

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (140) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (140) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (140) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.47838383838383836
Mean Precision: 0.47838383838383836
Mean Recall: 0.47838383838383836
learning rate 0.0005, epochs 160

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (160) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (160) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (160) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.4188888888888889
Mean Precision: 0.4188888888888889
Mean Recall: 0.4188888888888889
learning rate 0.0005, epochs 180

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (180) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (180) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (180) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.45020202020202016
Mean Precision: 0.45020202020202016
Mean Recall: 0.45020202020202016
learning rate 0.0005, epochs 200

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.4915151515151515
Mean Precision: 0.4915151515151515
Mean Recall: 0.4915151515151515
learning rate 0.0001, epochs 20

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.20555555555555555
Mean Precision: 0.20555555555555555
Mean Recall: 0.20555555555555555
learning rate 0.0001, epochs 40

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (40) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.21010101010101007
Mean Precision: 0.21010101010101007
Mean Recall: 0.21010101010101007
learning rate 0.0001, epochs 60

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (60) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.29444444444444445
Mean Precision: 0.29444444444444445
Mean Recall: 0.29444444444444445
learning rate 0.0001, epochs 80

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (80) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (80) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (80) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.32303030303030306
Mean Precision: 0.32303030303030306
Mean Recall: 0.32303030303030306
learning rate 0.0001, epochs 100

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.3301010101010101
Mean Precision: 0.3301010101010101
Mean Recall: 0.3301010101010101
learning rate 0.0001, epochs 120

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (120) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.34454545454545454
Mean Precision: 0.34454545454545454
Mean Recall: 0.34454545454545454
learning rate 0.0001, epochs 140
Mean Accuracy: 0.33565656565656565
Mean Precision: 0.33565656565656565
Mean Recall: 0.33565656565656565
learning rate 0.0001, epochs 160

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (160) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.27797979797979794
Mean Precision: 0.27797979797979794
Mean Recall: 0.27797979797979794
learning rate 0.0001, epochs 180

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (180) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.2588888888888889
Mean Precision: 0.2588888888888889
Mean Recall: 0.2588888888888889
learning rate 0.0001, epochs 200

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Mean Accuracy: 0.34797979797979794
Mean Precision: 0.34797979797979794
Mean Recall: 0.34797979797979794

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

In [ ]:
#print(results)
rounded_data = [[round(value, 2) for value in row] for row in results]
for i in rounded_data:
  print("\t".join(map(str, i))) # Tab-separated values

0.24	0.2	0.25	0.25	0.24	0.19	0.28	0.24	0.25	0.2
0.24	0.34	0.38	0.47	0.47	0.53	0.56	0.48	0.53	0.54
0.34	0.25	0.29	0.36	0.44	0.29	0.34	0.43	0.35	0.38
0.26	0.28	0.48	0.47	0.34	0.5	0.51	0.3	0.52	0.35
0.23	0.32	0.43	0.39	0.35	0.44	0.48	0.42	0.45	0.49
0.21	0.21	0.29	0.32	0.33	0.34	0.34	0.28	0.26	0.35

### Fit the best model

- Select the best model having the highest cross validation accuracy

In [ ]:
# Model with the lowest RMSE or highest r2
best_model = RandomForestClassifier(n_estimators=10, max_depth = 5)


# Fit the model on the full training dataset
best_model.fit(X, Y)

RandomForestClassifier(max_depth=5, n_estimators=10)

In [ ]:
import pickle
# Load the trained model
with open("/content/drive/MyDrive/Raeyaan shared folder/Exoskeleton Project/models/randomForest_model_19_7.pkl", "wb") as model_file:
  pickle.dump(best_model, model_file)

### Save the best model

- Make sure to donwload the model when you are planning to use the model later.