<a href="https://colab.research.google.com/github/raeyaanmuppaneni/EMG-controlled-robotic-arm/blob/main/Data_Preprocessing_and_feature_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Objective
- combine all the data in a single csv file

Steps to follow:
1. Load and visualize the data
2. create a master

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Load and visualize data

In [ ]:
sample_data = "/content/drive/MyDrive/Technology and Trainings/Python and AI/Raeyaan/Raeyaan shared folder/Exoskeleton Project/Dataset/hand_lift/hand_lift_1.csv"
# sample_data = "/content/drive/MyDrive/Raeyaan shared folder/Exoskeleton Project/Dataset/combined_data_EMG_envelope_updated.csv"

In [ ]:
import pandas as pd

df = pd.read_csv(sample_data)

In [ ]:
df.head()

,exo_project_emg_1_emg_filtered,exo_project_emg_1_emg_envelop,exo_project_emg_1_x,exo_project_emg_1_y,exo_project_emg_1_z
0,-54,256,4,3,-7
1,-70,256,4,3,-7
2,-50,256,4,3,-7
3,4,256,4,3,-7
4,62,256,4,4,-7

In [ ]:
df.describe()

,exo_project_emg_1_emg_envelop_0,exo_project_emg_1_emg_envelop_1,exo_project_emg_1_emg_envelop_2,exo_project_emg_1_emg_envelop_3,exo_project_emg_1_emg_envelop_4,exo_project_emg_1_emg_envelop_5,exo_project_emg_1_emg_envelop_6,exo_project_emg_1_emg_envelop_7,exo_project_emg_1_emg_envelop_8,exo_project_emg_1_emg_envelop_9,...,exo_project_emg_1_emg_envelop_50,exo_project_emg_1_emg_envelop_51,exo_project_emg_1_emg_envelop_52,exo_project_emg_1_emg_envelop_53,exo_project_emg_1_emg_envelop_54,exo_project_emg_1_emg_envelop_55,exo_project_emg_1_emg_envelop_56,exo_project_emg_1_emg_envelop_57,exo_project_emg_1_emg_envelop_58,exo_project_emg_1_emg_envelop_59
count,200.00000,200.000000,200.000000,200.000000,200.00000,200.000000,200.000000,200.000000,200.00000,200.000000,...,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,435.20000,433.940000,432.360000,431.210000,428.99000,427.660000,425.360000,423.860000,421.36000,420.070000,...,445.610000,445.660000,445.780000,445.780000,445.780000,445.980000,445.950000,445.820000,445.680000,445.860000
std,251.85399,252.843282,252.687247,253.517398,253.53255,254.378273,254.327669,255.557604,255.43096,256.590743,...,244.134463,243.382703,243.843742,243.386723,243.658035,243.470633,243.672277,243.749207,243.828133,244.254132
min,106.00000,104.000000,104.000000,102.000000,102.00000,104.000000,102.000000,104.000000,104.00000,104.000000,...,142.000000,142.000000,142.000000,140.000000,138.000000,136.000000,134.000000,134.000000,134.000000,134.000000
25%,228.00000,227.000000,223.500000,222.000000,220.00000,218.000000,218.000000,217.500000,216.00000,214.000000,...,233.500000,233.500000,234.000000,235.500000,237.000000,239.000000,238.500000,238.000000,239.500000,239.000000
50%,364.00000,364.000000,362.000000,358.000000,355.00000,353.000000,349.000000,342.000000,337.00000,335.000000,...,407.000000,408.000000,405.000000,401.000000,397.000000,393.000000,390.000000,388.000000,386.000000,385.000000
75%,556.50000,550.500000,549.000000,545.500000,544.50000,542.000000,537.500000,530.500000,529.00000,528.500000,...,563.500000,563.500000,563.000000,563.000000,564.000000,563.500000,563.500000,559.500000,561.000000,562.500000
max,1166.00000,1162.000000,1154.000000,1158.000000,1152.00000,1160.000000,1156.000000,1162.000000,1160.00000,1162.000000,...,1112.000000,1112.000000,1112.000000,1114.000000,1114.000000,1114.000000,1114.000000,1116.000000,1114.000000,1118.000000

#Method 0: Using Raw EMG Enveloped Values

In [ ]:
import os
import pandas as pd

# Path to the main folder containing all subfolders
main_folder = "/content/drive/MyDrive/Raeyaan shared folder/Exoskeleton Project/Dataset/Raeyaan Dataset"  # Change this to the actual path

# List to store combined data
final_data = []
column_names = None  # To store column names from the first file

# Iterate through each folder in the main directory
for folder in os.listdir(main_folder):
    folder_path = os.path.join(main_folder, folder)

    # Ensure it's a directory
    if os.path.isdir(folder_path):
        for file in os.listdir(folder_path):
            if file.endswith(".csv"):  # Process only CSV files
                file_path = os.path.join(folder_path, file)

                # Read the CSV file
                df = pd.read_csv(file_path)
                df = df[["exo_project_emg_1_emg_envelop"]]
                # Flatten the data into a single row
                row_data = df.values.flatten().tolist()

                # Append folder name as a new column
                row_data.append(folder)

                # Store column names only from the first file
                if column_names is None:
                    original_columns = list(df.columns)
                    expanded_column_names = [f"{col}_{i}" for i in range(len(df)) for col in original_columns]
                    expanded_column_names.append("Folder")  # Add folder column
                    column_names = expanded_column_names  # Store column names

                # Store the row
                final_data.append(row_data)

# Create a DataFrame with all collected rows
final_df = pd.DataFrame(final_data, columns=column_names)

# Save the final DataFrame as a CSV file
final_csv_path = os.path.join(main_folder, "combined_data_EMG_envelop_20_7.csv")
final_df.to_csv(final_csv_path, index=False)

print(f"Final CSV saved at: {final_csv_path}")

Final CSV saved at: /content/drive/MyDrive/Raeyaan shared folder/Exoskeleton Project/Dataset/Raeyaan Dataset/combined_data_EMG_envelop_20_7.csv

In [ ]:
final_df.columns

Index(['exo_project_emg_1_emg_envelop_0', 'exo_project_emg_1_emg_envelop_1',
       'exo_project_emg_1_emg_envelop_2', 'exo_project_emg_1_emg_envelop_3',
       'exo_project_emg_1_emg_envelop_4', 'exo_project_emg_1_emg_envelop_5',
       'exo_project_emg_1_emg_envelop_6', 'exo_project_emg_1_emg_envelop_7',
       'exo_project_emg_1_emg_envelop_8', 'exo_project_emg_1_emg_envelop_9',
       'exo_project_emg_1_emg_envelop_10', 'exo_project_emg_1_emg_envelop_11',
       'exo_project_emg_1_emg_envelop_12', 'exo_project_emg_1_emg_envelop_13',
       'exo_project_emg_1_emg_envelop_14', 'exo_project_emg_1_emg_envelop_15',
       'exo_project_emg_1_emg_envelop_16', 'exo_project_emg_1_emg_envelop_17',
       'exo_project_emg_1_emg_envelop_18', 'exo_project_emg_1_emg_envelop_19',
       'exo_project_emg_1_emg_envelop_20', 'exo_project_emg_1_emg_envelop_21',
       'exo_project_emg_1_emg_envelop_22', 'exo_project_emg_1_emg_envelop_23',
       'exo_project_emg_1_emg_envelop_24', 'exo_project_emg_1_emg_envelop_25',
       'exo_project_emg_1_emg_envelop_26', 'exo_project_emg_1_emg_envelop_27',
       'exo_project_emg_1_emg_envelop_28', 'exo_project_emg_1_emg_envelop_29',
       'exo_project_emg_1_emg_envelop_30', 'exo_project_emg_1_emg_envelop_31',
       'exo_project_emg_1_emg_envelop_32', 'exo_project_emg_1_emg_envelop_33',
       'exo_project_emg_1_emg_envelop_34', 'exo_project_emg_1_emg_envelop_35',
       'exo_project_emg_1_emg_envelop_36', 'exo_project_emg_1_emg_envelop_37',
       'exo_project_emg_1_emg_envelop_38', 'exo_project_emg_1_emg_envelop_39',
       'exo_project_emg_1_emg_envelop_40', 'exo_project_emg_1_emg_envelop_41',
       'exo_project_emg_1_emg_envelop_42', 'exo_project_emg_1_emg_envelop_43',
       'exo_project_emg_1_emg_envelop_44', 'exo_project_emg_1_emg_envelop_45',
       'exo_project_emg_1_emg_envelop_46', 'exo_project_emg_1_emg_envelop_47',
       'exo_project_emg_1_emg_envelop_48', 'exo_project_emg_1_emg_envelop_49',
       'exo_project_emg_1_emg_envelop_50', 'exo_project_emg_1_emg_envelop_51',
       'exo_project_emg_1_emg_envelop_52', 'exo_project_emg_1_emg_envelop_53',
       'exo_project_emg_1_emg_envelop_54', 'exo_project_emg_1_emg_envelop_55',
       'exo_project_emg_1_emg_envelop_56', 'exo_project_emg_1_emg_envelop_57',
       'exo_project_emg_1_emg_envelop_58', 'exo_project_emg_1_emg_envelop_59',
       'Folder'],
      dtype='object')

# Method 1: Using Raw data to classify

## Create a combined csv file with all the data points and corresponding labels

In [ ]:
import os
import pandas as pd

# Path to the main folder containing all subfolders
main_folder = "/content/drive/MyDrive/Technology and Trainings/Python and AI/Raeyaan/Raeyaan shared folder/Exoskeleton Project/Dataset"  # Change this to the actual path

# List to store combined data
final_data = []
column_names = None  # To store column names from the first file

# Iterate through each folder in the main directory
for folder in os.listdir(main_folder):
    folder_path = os.path.join(main_folder, folder)

    # Ensure it's a directory
    if os.path.isdir(folder_path):
        for file in os.listdir(folder_path):
            if file.endswith(".csv"):  # Process only CSV files
                file_path = os.path.join(folder_path, file)

                # Read the CSV file
                df = pd.read_csv(file_path)

                # Flatten the data into a single row
                row_data = df.values.flatten().tolist()

                # Append folder name as a new column
                row_data.append(folder)

                # Store column names only from the first file
                if column_names is None:
                    original_columns = list(df.columns)
                    expanded_column_names = [f"{col}_{i}" for i in range(len(df)) for col in original_columns]
                    expanded_column_names.append("Folder")  # Add folder column
                    column_names = expanded_column_names  # Store column names

                # Store the row
                final_data.append(row_data)

# Create a DataFrame with all collected rows
final_df = pd.DataFrame(final_data, columns=column_names)

# Save the final DataFrame as a CSV file
final_csv_path = os.path.join(main_folder, "combined_data.csv")
final_df.to_csv(final_csv_path, index=False)

print(f"Final CSV saved at: {final_csv_path}")

Final CSV saved at: /content/drive/MyDrive/Technology and Trainings/Python and AI/Raeyaan/Raeyaan shared folder/Exoskeleton Project/Dataset/combined_data.csv

In [ ]:
final_df.tail()

,exo_project_emg_1_emg_filtered_0,exo_project_emg_1_emg_envelop_0,exo_project_emg_1_x_0,exo_project_emg_1_y_0,exo_project_emg_1_z_0,exo_project_emg_1_emg_filtered_1,exo_project_emg_1_emg_envelop_1,exo_project_emg_1_x_1,exo_project_emg_1_y_1,exo_project_emg_1_z_1,...,exo_project_emg_1_emg_envelop_58,exo_project_emg_1_x_58,exo_project_emg_1_y_58,exo_project_emg_1_z_58,exo_project_emg_1_emg_filtered_59,exo_project_emg_1_emg_envelop_59,exo_project_emg_1_x_59,exo_project_emg_1_y_59,exo_project_emg_1_z_59,Folder
145,12,452,8,1,-4,-215,454,8,1,-4,...,524,8,0,-5,149,526,8,0,-5,hand_lift
146,137,510,8,0,-5,116,510,8,0,-5,...,528,8,0,-5,350,530,8,0,-5,hand_lift
147,-418,540,8,0,-4,-536,544,8,1,-5,...,574,8,1,-5,-104,572,8,1,-5,hand_lift
148,-115,558,8,1,-5,15,552,8,1,-4,...,470,8,1,-5,401,472,7,0,-5,hand_lift
149,-7,496,8,1,-4,234,498,8,1,-4,...,490,8,1,-4,-194,492,8,1,-5,hand_lift

# Method 2: Featrurization using tsfresh

In [ ]:
!pip install tsfresh[dask] -q
!pip install  scipy==1.14.0
!pip install pandas==2.2.2 -q

Collecting scipy==1.14.0
  Downloading scipy-1.14.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 2.0 MB/s eta 0:00:00
Requirement already satisfied: numpy<2.3,>=1.23.5 in /usr/local/lib/python3.11/dist-packages (from scipy==1.14.0) (2.0.2)
Downloading scipy-1.14.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.1/41.1 MB 28.2 MB/s eta 0:00:00
Installing collected packages: scipy
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
Successfully installed scipy-1.14.0

In [ ]:
import os
import pandas as pd
from tsfresh.feature_extraction import extract_features

# Path to the main folder containing all subfolders
main_folder = "/content/drive/MyDrive/Raeyaan shared folder/Exoskeleton Project/Dataset/Raeyaan Dataset" # Change this to your actual folder path

# List to store processed data
final_data = []

# Iterate through each folder in the main directory
for folder in os.listdir(main_folder):
    folder_path = os.path.join(main_folder, folder)

    if os.path.isdir(folder_path):  # Ensure it's a directory
        for file in os.listdir(folder_path):
            if file.endswith(".csv"):  # Process only CSV files
                file_path = os.path.join(folder_path, file)

                # Read the CSV file
                df = pd.read_csv(file_path)

                # ✅ Format CSV: Add 'id' and 'time' columns
                df["id"] = range(1, len(df) + 1)  # 1 to 60
                df["time"] = range(1, len(df) + 1)  # 1 to 60

                # ✅ Keep only 'id', 'time', and 'emg_envelop' columns
                if 'exo_project_emg_1_emg_envelop' not in df.columns:
                    print(f"Skipping {file} (no 'exo_project_emg_1_emg_envelop' column)")
                    continue

                df = df[["id", "time", "exo_project_emg_1_emg_envelop"]]

                # ✅ Extract features using tsfresh (only on 'emg_envelop')
                extracted_features = extract_features(df, column_id='id', column_sort='time')

                # Flatten extracted features into a single row
                row_data = extracted_features.iloc[0].tolist()

                # Append folder name as a new column
                row_data.append(folder)

                # Store the processed row
                final_data.append(row_data)

# ✅ Create a DataFrame with extracted features
feature_columns = list(extracted_features.columns)  # Get feature names
feature_columns.append("Folder")  # Add folder column

final_df = pd.DataFrame(final_data, columns=feature_columns)

# ✅ Save the final DataFrame as a CSV file
final_csv_path = os.path.join(main_folder, "tsfresh_updated.csv")
final_df.to_csv(final_csv_path, index=False)

print(f"Feature CSV saved at: {final_csv_path}")

WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.06it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 12.02it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.55it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.45it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 12.01it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.29it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.38it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.75it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.43it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.17it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.87it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.20it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.91it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.79it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.68it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.39it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.90it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.80it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.21it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 10.92it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.90it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.40it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.70it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.46it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.14it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.54it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.12it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.43it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.59it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.84it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.11it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.48it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 12.85it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.67it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.21it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.14it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.12it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.31it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.32it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.23it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.33it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.88it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.27it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.25it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.19it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.05it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.25it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.27it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.27it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.22it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.15it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.37it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.37it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.39it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.78it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.32it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.17it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.16it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.21it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.28it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.15it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.30it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.38it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.20it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.33it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.15it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.11it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.39it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.05it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.29it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.20it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.21it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.25it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.11it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.18it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.32it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.19it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.05it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.07it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.59it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.09it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.50it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.73it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.31it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.40it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.71it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.19it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.26it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.73it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.10it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.32it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.85it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.21it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.36it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.76it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.15it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.09it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:05<00:00, 11.83it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 13.99it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 12.88it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 12.29it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.13it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 12.79it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 12.35it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 14.09it/s]
WARNING:tsfresh.feature_extraction.settings:Dependency not available for matrix_profile, this feature will be disabled!
Feature Extraction: 100%|██████████| 60/60 [00:04<00:00, 12.64it/s]

Feature CSV saved at: /content/drive/MyDrive/Raeyaan shared folder/Exoskeleton Project/Dataset/Raeyaan Dataset/tsfresh_updated.csv

In [ ]:
len(final_df.columns)

784

In [ ]:
import pandas as pd
df1 = pd.read_csv("/content/drive/MyDrive/Raeyaan shared folder/Exoskeleton Project/Dataset/Raeyaan Dataset/tsfresh_updated.csv")
df1.head()

,exo_project_emg_1_emg_envelop__variance_larger_than_standard_deviation,exo_project_emg_1_emg_envelop__has_duplicate_max,exo_project_emg_1_emg_envelop__has_duplicate_min,exo_project_emg_1_emg_envelop__has_duplicate,exo_project_emg_1_emg_envelop__sum_values,exo_project_emg_1_emg_envelop__abs_energy,exo_project_emg_1_emg_envelop__mean_abs_change,exo_project_emg_1_emg_envelop__mean_change,exo_project_emg_1_emg_envelop__mean_second_derivative_central,exo_project_emg_1_emg_envelop__median,...,exo_project_emg_1_emg_envelop__fourier_entropy__bins_10,exo_project_emg_1_emg_envelop__fourier_entropy__bins_100,exo_project_emg_1_emg_envelop__permutation_entropy__dimension_3__tau_1,exo_project_emg_1_emg_envelop__permutation_entropy__dimension_4__tau_1,exo_project_emg_1_emg_envelop__permutation_entropy__dimension_5__tau_1,exo_project_emg_1_emg_envelop__permutation_entropy__dimension_6__tau_1,exo_project_emg_1_emg_envelop__permutation_entropy__dimension_7__tau_1,exo_project_emg_1_emg_envelop__query_similarity_count__query_None__threshold_0.0,exo_project_emg_1_emg_envelop__mean_n_absolute_max__number_of_maxima_7,Folder
0,0.0,0.0,0.0,0.0,270.0,72900.0,NaN,NaN,NaN,270.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hand Lift
1,0.0,0.0,0.0,0.0,204.0,41616.0,NaN,NaN,NaN,204.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hand Lift
2,0.0,0.0,0.0,0.0,352.0,123904.0,NaN,NaN,NaN,352.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hand Lift
3,0.0,0.0,0.0,0.0,272.0,73984.0,NaN,NaN,NaN,272.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hand Lift
4,0.0,0.0,0.0,0.0,264.0,69696.0,NaN,NaN,NaN,264.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hand Lift

## Clean columns with NAN and zeroes

In [ ]:

# Remove columns that contain any NaN values
df_cleaned_1 = df1.dropna(axis=1)
# Remove columns where all values are zero
df_cleaned = df_cleaned_1.loc[:, (df_cleaned_1 != 0).any(axis=0)]

# Save the cleaned CSV file
cleaned_file_path = '/content/drive/MyDrive/Raeyaan shared folder/Exoskeleton Project/Dataset/Raeyaan Dataset/tsfresh_updated1.csv'
df_cleaned.to_csv(cleaned_file_path, index=False)

# Return the cleaned file path
cleaned_file_path

'/content/drive/MyDrive/Raeyaan shared folder/Exoskeleton Project/Dataset/Raeyaan Dataset/tsfresh_updated1.csv'

# Method 3: Featurization using Librosa and extracting MFCC features

In [ ]:
!pip install librosa -q

In [ ]:
import os
import pandas as pd
import numpy as np
import librosa

# Path to the main folder containing all subfolders
main_folder = "/content/drive/MyDrive/Raeyaan shared folder/Exoskeleton Project/Dataset/Raeyaan Dataset"  # Change this to your actual folder path

# List to store processed data
final_data = []

# Number of MFCC coefficients to extract
n_mfcc = 20  # You can adjust this based on your needs

# Iterate through each folder in the main directory
for folder in os.listdir(main_folder):
    folder_path = os.path.join(main_folder, folder)

    if os.path.isdir(folder_path):  # Ensure it's a directory
        for file in os.listdir(folder_path):
            if file.endswith(".csv"):  # Process only CSV files
                file_path = os.path.join(folder_path, file)

                # Read the CSV file
                df = pd.read_csv(file_path)

                # ✅ Ensure the 'emg_envelop' column exists
                if 'exo_project_emg_1_emg_envelop' not in df.columns:
                    print(f"Skipping {file} (no 'exo_project_emg_1_emg_envelop' column)")
                    continue

                # Convert EMG data to numpy array
                emg_signal = df["exo_project_emg_1_emg_envelop"].values.astype(float)

                # Compute MFCC features (treating EMG as a signal)
                mfccs = librosa.feature.mfcc(y=emg_signal, sr=1000, n_mfcc=n_mfcc)  # Assuming sr=1000 Hz

                # Compute statistical features for each MFCC coefficient
                mfcc_features = np.mean(mfccs, axis=1)  # Taking mean of each coefficient

                # Append folder name as a new column
                row_data = mfcc_features.tolist()
                row_data.append(folder)

                # Store the processed row
                final_data.append(row_data)

# ✅ Create a DataFrame with extracted MFCC features
mfcc_columns = [f"MFCC_{i+1}" for i in range(n_mfcc)]  # Create column names
mfcc_columns.append("Folder")  # Add folder column

final_df = pd.DataFrame(final_data, columns=mfcc_columns)

# ✅ Save the final DataFrame as a CSV file
final_csv_path = os.path.join(main_folder, "mfcc.csv")
final_df.to_csv(final_csv_path, index=False)

print(f"MFCC feature CSV saved at: {final_csv_path}")

/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=60
  warnings.warn(

MFCC feature CSV saved at: /content/drive/MyDrive/Raeyaan shared folder/Exoskeleton Project/Dataset/Raeyaan Dataset/mfcc.csv

In [ ]:
df2 = pd.read_csv("/content/drive/MyDrive/Raeyaan shared folder/Exoskeleton Project/Dataset/processed_features_mfcc.csv")
df2.head()

,MFCC_1,MFCC_2,MFCC_3,MFCC_4,MFCC_5,MFCC_6,MFCC_7,MFCC_8,MFCC_9,MFCC_10,MFCC_11,MFCC_12,MFCC_13,Folder
0,623.028377,67.651286,32.951482,21.758012,16.136585,12.334915,10.418328,8.311194,7.694400,6.761437,6.031368,5.680634,5.441635,hand_twist
1,620.178389,66.572897,33.599099,21.612902,16.076634,12.477714,10.940593,8.250710,8.432313,5.870391,7.213943,4.454963,5.391588,hand_twist
2,633.987119,66.526644,33.763398,21.273566,16.093796,12.525531,10.993674,8.392450,8.263319,6.224502,6.317507,5.073386,5.405890,hand_twist
3,622.741698,66.771830,33.841192,21.598689,16.905180,12.269782,10.924183,8.687490,8.130254,6.436752,6.297815,5.047989,5.152913,hand_twist
4,643.932170,66.922063,34.021061,21.496996,16.500774,12.761347,10.976406,8.949864,8.407925,6.459672,6.813025,5.168112,5.214682,hand_twist

In [ ]:
df2["Folder"].unique()

array(['hand_twist', 'wrist_lift', 'hand_lift', 'Normal'], dtype=object)